version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - web-network

networks:
  web-network:
    driver: bridge